name: forglet
template: go

module: github.com/forgant-foundry/forglet
require:
  github.com/forgant-foundry/eventing: v1.0.0
  github.com/spf13/cobra: v1.8.0
  gopkg.in/yaml.v3: v3.0.1

git: true
gitignore:
  - /forglet

license:
  id: MIT
  author: Forgant

github:
  delivery:
    majorVersion: 1
    kind: library
