// ~~ Generated by forglet. To modify, edit .forglet.yml and run 'forglet synth' ~~
module github.com/forgant-foundry/forglet

go 1.25.5

require (
	github.com/forgant-foundry/eventing v0.0.0-20260427024055-dcc6fcefd427
	github.com/spf13/cobra v1.8.0
	gopkg.in/yaml.v3 v3.0.1
)

require (
	github.com/BurntSushi/toml v1.6.0 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
)
