package java

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/forgant-foundry/eventing"
	"github.com/forgant-foundry/forglet/internal/project"
)

const (
	defaultGroupID     = "com.example"
	defaultVersion     = "1.0.0-SNAPSHOT"
	defaultJavaVersion = "21"
	overlaySeqBase     = int64(1000)

	junitVersion    = "5.10.2"
	surefireVersion = "3.2.5"
	shadeVersion    = "3.5.2"

	pomManagedComment = "~~ Generated by forglet. To modify, edit .forglet.yml and run 'forglet synth' ~~"
)

// Flat synthesizes a plain single-module Maven project.
// Managed files: pom.xml
// Scaffolded once: src/main/java/.../App.java, src/test/java/.../AppTest.java
type Flat struct{}

func NewFlat() *Flat { return &Flat{} }

func (s *Flat) InitializeEvents(name string) (map[string][]eventing.Event, error) {
	events, err := makeEvents(1, []evtDef{
		{"init", map[string]any{
			"groupId":     defaultGroupID,
			"artifactId":  name,
			"version":     defaultVersion,
			"packaging":   "jar",
			"javaVersion": defaultJavaVersion,
		}},
		{"testDependency.added", map[string]any{
			"testDependencies": map[string]any{
				"org.junit.jupiter:junit-jupiter": junitVersion,
			},
		}},
	})
	if err != nil {
		return nil, err
	}
	return map[string][]eventing.Event{"pom.xml": events}, nil
}

// OverlayEvents supports rc keys: groupId, version, javaVersion,
// dependencies (map[string]string), testDependencies (map[string]string).
func (s *Flat) OverlayEvents(rc map[string]any) (map[string][]eventing.Event, error) {
	return commonOverlay(rc)
}

func (s *Flat) Synthesize(dir string, aggregates map[string]*eventing.Aggregate) error {
	agg, ok := aggregates["pom.xml"]
	if !ok {
		return nil
	}
	b, err := renderFlatPom(agg)
	if err != nil {
		return fmt.Errorf("render pom.xml: %w", err)
	}
	if err := project.WriteManaged(filepath.Join(dir, "pom.xml"), b); err != nil {
		return err
	}

	groupID := nodeStr(agg, "groupId", defaultGroupID)
	pkgDir := filepath.Join(dir, "src", "main", "java", groupToPath(groupID))
	testPkgDir := filepath.Join(dir, "src", "test", "java", groupToPath(groupID))

	mainFile := filepath.Join(pkgDir, "App.java")
	if _, err := os.Stat(mainFile); os.IsNotExist(err) {
		if err := os.MkdirAll(pkgDir, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(mainFile, appJava(groupID), 0644); err != nil {
			return err
		}
	}

	testFile := filepath.Join(testPkgDir, "AppTest.java")
	if _, err := os.Stat(testFile); os.IsNotExist(err) {
		if err := os.MkdirAll(testPkgDir, 0755); err != nil {
			return err
		}
		if err := os.WriteFile(testFile, appTestJava(groupID), 0644); err != nil {
			return err
		}
	}

	return nil
}

// ---- XML rendering helpers ----

func renderPomHeader(buf *bytes.Buffer) {
	fmt.Fprintf(buf, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	fmt.Fprintf(buf, "<!-- %s -->\n", pomManagedComment)
	fmt.Fprintf(buf, "<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n")
	fmt.Fprintf(buf, "         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n")
	fmt.Fprintf(buf, "         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n")
	fmt.Fprintf(buf, "    <modelVersion>4.0.0</modelVersion>\n\n")
}

func renderPomCoords(buf *bytes.Buffer, agg *eventing.Aggregate) {
	writeln(buf, 1, "groupId", nodeStr(agg, "groupId", defaultGroupID))
	writeln(buf, 1, "artifactId", nodeStr(agg, "artifactId", "app"))
	writeln(buf, 1, "version", nodeStr(agg, "version", defaultVersion))
	writeln(buf, 1, "packaging", nodeStr(agg, "packaging", "jar"))
	fmt.Fprintf(buf, "\n")
}

func renderProperties(buf *bytes.Buffer, agg *eventing.Aggregate) {
	jv := nodeStr(agg, "javaVersion", defaultJavaVersion)
	fmt.Fprintf(buf, "    <properties>\n")
	writeln(buf, 2, "maven.compiler.source", jv)
	writeln(buf, 2, "maven.compiler.target", jv)
	writeln(buf, 2, "project.build.sourceEncoding", "UTF-8")
	fmt.Fprintf(buf, "    </properties>\n\n")
}

func renderDependencies(buf *bytes.Buffer, agg *eventing.Aggregate) {
	compile := activeDeps(agg, "dependencies", "")
	test := activeDeps(agg, "testDependencies", "test")
	all := append(compile, test...)
	if len(all) == 0 {
		return
	}
	fmt.Fprintf(buf, "    <dependencies>\n")
	for _, d := range all {
		fmt.Fprintf(buf, "        <dependency>\n")
		writeln(buf, 3, "groupId", d.groupID)
		writeln(buf, 3, "artifactId", d.artifactID)
		if d.version != "" {
			writeln(buf, 3, "version", d.version)
		}
		if d.scope != "" {
			writeln(buf, 3, "scope", d.scope)
		}
		fmt.Fprintf(buf, "        </dependency>\n")
	}
	fmt.Fprintf(buf, "    </dependencies>\n\n")
}

func renderBuild(buf *bytes.Buffer, plugins []pomPlugin) {
	if len(plugins) == 0 {
		return
	}
	fmt.Fprintf(buf, "    <build>\n")
	fmt.Fprintf(buf, "        <plugins>\n")
	for _, p := range plugins {
		fmt.Fprintf(buf, "            <plugin>\n")
		writeln(buf, 4, "groupId", p.groupID)
		writeln(buf, 4, "artifactId", p.artifactID)
		if p.version != "" {
			writeln(buf, 4, "version", p.version)
		}
		if p.extra != "" {
			fmt.Fprint(buf, p.extra)
		}
		fmt.Fprintf(buf, "            </plugin>\n")
	}
	fmt.Fprintf(buf, "        </plugins>\n")
	fmt.Fprintf(buf, "    </build>\n")
}

func renderFlatPom(agg *eventing.Aggregate) ([]byte, error) {
	var buf bytes.Buffer
	renderPomHeader(&buf)
	renderPomCoords(&buf, agg)
	renderProperties(&buf, agg)
	renderDependencies(&buf, agg)
	renderBuild(&buf, []pomPlugin{surefirePlugin()})
	fmt.Fprintf(&buf, "</project>\n")
	return buf.Bytes(), nil
}

// ---- plugin descriptors ----

type pomPlugin struct {
	groupID    string
	artifactID string
	version    string
	extra      string // indented XML for <executions> / <configuration>, or ""
}

func surefirePlugin() pomPlugin {
	return pomPlugin{
		groupID:    "org.apache.maven.plugins",
		artifactID: "maven-surefire-plugin",
		version:    surefireVersion,
	}
}

func shadePlugin() pomPlugin {
	return pomPlugin{
		groupID:    "org.apache.maven.plugins",
		artifactID: "maven-shade-plugin",
		version:    shadeVersion,
		extra: "                <executions>\n" +
			"                    <execution>\n" +
			"                        <phase>package</phase>\n" +
			"                        <goals><goal>shade</goal></goals>\n" +
			"                        <configuration>\n" +
			"                            <createDependencyReducedPom>false</createDependencyReducedPom>\n" +
			"                        </configuration>\n" +
			"                    </execution>\n" +
			"                </executions>\n",
	}
}

// ---- dependency helpers ----

type dep struct {
	groupID    string
	artifactID string
	version    string
	scope      string
}

func activeDeps(agg *eventing.Aggregate, key, scope string) []dep {
	node, ok := agg.Node(key)
	if !ok {
		return nil
	}
	obj, ok := node.Value.(eventing.Object)
	if !ok {
		return nil
	}
	var deps []dep
	for _, n := range obj {
		if n.Status != eventing.NodeActive {
			continue
		}
		parts := strings.SplitN(n.Name, ":", 2)
		if len(parts) != 2 {
			continue
		}
		version, _ := n.Value.(string)
		deps = append(deps, dep{
			groupID:    parts[0],
			artifactID: parts[1],
			version:    version,
			scope:      scope,
		})
	}
	sort.Slice(deps, func(i, j int) bool {
		return deps[i].groupID+deps[i].artifactID < deps[j].groupID+deps[j].artifactID
	})
	return deps
}

// ---- XML low-level helpers ----

// writeln writes a single <tag>value</tag> line at the given indent level (4 spaces each).
func writeln(buf *bytes.Buffer, indent int, tag, value string) {
	prefix := strings.Repeat("    ", indent)
	fmt.Fprintf(buf, "%s<%s>%s</%s>\n", prefix, tag, esc(value), tag)
}

func esc(s string) string {
	var b bytes.Buffer
	xml.EscapeText(&b, []byte(s))
	return b.String()
}

// ---- path / aggregate helpers ----

// groupToPath converts "com.example" → "com/example" (OS-appropriate separator).
func groupToPath(groupID string) string {
	return filepath.Join(strings.Split(groupID, ".")...)
}

func nodeStr(agg *eventing.Aggregate, key, def string) string {
	n, ok := agg.Node(key)
	if !ok {
		return def
	}
	s, _ := n.Value.(string)
	if s == "" {
		return def
	}
	return s
}

// ---- scaffold content ----

func appJava(pkg string) []byte {
	return []byte("package " + pkg + ";\n\npublic class App {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}\n")
}

func appTestJava(pkg string) []byte {
	return []byte("package " + pkg + ";\n\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass AppTest {\n    @Test\n    void appInstantiates() {\n        assertNotNull(new App());\n    }\n}\n")
}

// ---- event helpers ----

type evtDef struct {
	typ     string
	payload any
}

func makeEvents(base int64, defs []evtDef) ([]eventing.Event, error) {
	evts := make([]eventing.Event, len(defs))
	for i, d := range defs {
		b, err := json.Marshal(d.payload)
		if err != nil {
			return nil, err
		}
		evts[i] = eventing.Event{
			ID:      newID(),
			Type:    d.typ,
			Seq:     base + int64(i),
			Payload: json.RawMessage(b),
		}
	}
	return evts, nil
}

func commonOverlay(rc map[string]any) (map[string][]eventing.Event, error) {
	if len(rc) == 0 {
		return nil, nil
	}
	var defs []evtDef
	if v, ok := rc["groupId"].(string); ok && v != "" {
		defs = append(defs, evtDef{"groupId.set", map[string]any{"groupId": v}})
	}
	if v, ok := rc["version"].(string); ok && v != "" {
		defs = append(defs, evtDef{"version.set", map[string]any{"version": v}})
	}
	if v, ok := rc["javaVersion"].(string); ok && v != "" {
		defs = append(defs, evtDef{"javaVersion.set", map[string]any{"javaVersion": v}})
	}
	if deps, ok := asStringMap(rc["dependencies"]); ok {
		anyDeps := make(map[string]any, len(deps))
		for k, v := range deps {
			anyDeps[k] = v
		}
		defs = append(defs, evtDef{"dependency.added", map[string]any{"dependencies": anyDeps}})
	}
	if deps, ok := asStringMap(rc["testDependencies"]); ok {
		anyDeps := make(map[string]any, len(deps))
		for k, v := range deps {
			anyDeps[k] = v
		}
		defs = append(defs, evtDef{"testDependency.added", map[string]any{"testDependencies": anyDeps}})
	}
	if len(defs) == 0 {
		return nil, nil
	}
	events, err := makeEvents(overlaySeqBase, defs)
	if err != nil {
		return nil, err
	}
	return map[string][]eventing.Event{"pom.xml": events}, nil
}

func asStringMap(v any) (map[string]string, bool) {
	raw, ok := v.(map[string]any)
	if !ok || len(raw) == 0 {
		return nil, false
	}
	out := make(map[string]string, len(raw))
	for k, val := range raw {
		s, ok := val.(string)
		if !ok {
			continue
		}
		out[k] = s
	}
	return out, len(out) > 0
}

func asStringSlice(v any) ([]string, bool) {
	raw, ok := v.([]any)
	if !ok || len(raw) == 0 {
		return nil, false
	}
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out, len(out) > 0
}

func newID() string {
	b := make([]byte, 8)
	rand.Read(b)
	return fmt.Sprintf("%x", b)
}
