package project

import (
	"bytes"
	"os"
)

const managedMarker = "~~ Generated by forglet. To modify, edit .forglet.yml and run 'forglet synth' ~~"

// WriteManaged writes content to path with read-only permissions (0444).
// If the file already exists (and is read-only), it is made writable before overwriting.
func WriteManaged(path string, content []byte) error {
	if _, err := os.Stat(path); err == nil {
		if err := os.Chmod(path, 0644); err != nil {
			return err
		}
	}
	return os.WriteFile(path, content, 0444)
}

// AddJSONMarker inserts a "//" comment key as the first field in a
// pretty-printed JSON object (output of json.MarshalIndent with "", "  ").
func AddJSONMarker(data []byte) []byte {
	const prefix = "{\n"
	if !bytes.HasPrefix(data, []byte(prefix)) {
		return data
	}
	line := `  "//": "` + managedMarker + `",` + "\n"
	out := make([]byte, 0, len(data)+len(line))
	out = append(out, []byte(prefix)...)
	out = append(out, []byte(line)...)
	out = append(out, data[len(prefix):]...)
	return out
}

// AddTextMarker prepends a comment line to text content.
// commentPrefix is the language comment character(s), e.g. "//" or "#".
func AddTextMarker(data []byte, commentPrefix string) []byte {
	line := commentPrefix + " " + managedMarker + "\n"
	out := make([]byte, 0, len(line)+len(data))
	out = append(out, []byte(line)...)
	out = append(out, data...)
	return out
}
